CREATE TABLE IF NOT EXISTS users (
id INT AUTO_INCREMENT PRIMARY KEY,
username VARCHAR(55) NOT NULL CHECK (CHAR_LENGTH(username) >= 4),
email VARCHAR(100) NOT NULL UNIQUE,
password VARCHAR(255) NOT NULL CHECK (CHAR_LENGTH(password) >= 8),
isAdmin BOOLEAN DEFAULT FALSE
);
